const names = [{"id":1,"first_name":"Bent","last_name":"Welds","email":"bwelds0@mail.ru","gender":"Male"},
{"id":2,"first_name":"Eda","last_name":"Pankettman","email":"epankettman1@cam.ac.uk","gender":"Female"},
{"id":3,"first_name":"Reinaldo","last_name":"Thackray","email":"rthackray2@vk.com","gender":"Male"},
{"id":4,"first_name":"Siffre","last_name":"Golbourn","email":"sgolbourn3@newsvine.com","gender":"Male"},
{"id":5,"first_name":"Stevy","last_name":"Geary","email":"sgeary4@ameblo.jp","gender":"Male"},
{"id":6,"first_name":"Siusan","last_name":"McFater","email":"smcfater5@latimes.com","gender":"Female"},
{"id":7,"first_name":"Udall","last_name":"Meikle","email":"umeikle6@princeton.edu","gender":"Male"},
{"id":8,"first_name":"Rosabel","last_name":"Heighway","email":"rheighway7@jigsy.com","gender":"Female"},
{"id":9,"first_name":"Aubert","last_name":"Rosenschein","email":"arosenschein8@blogtalkradio.com","gender":"Male"},
{"id":10,"first_name":"Skipton","last_name":"McCaighey","email":"smccaighey9@craigslist.org","gender":"Male"},
{"id":11,"first_name":"Svend","last_name":"Porte","email":"sportea@businessweek.com","gender":"Male"},
{"id":12,"first_name":"Jo","last_name":"Tinson","email":"jtinsonb@mapquest.com","gender":"Female"},
{"id":13,"first_name":"Vasilis","last_name":"Leeson","email":"vleesonc@hp.com","gender":"Male"},
{"id":14,"first_name":"Michale","last_name":"Lammert","email":"mlammertd@senate.gov","gender":"Male"},
{"id":15,"first_name":"Melisande","last_name":"Garrow","email":"mgarrowe@fema.gov","gender":"Female"},
{"id":16,"first_name":"Gabi","last_name":"Vondrak","email":"gvondrakf@about.me","gender":"Male"},
{"id":17,"first_name":"Allyn","last_name":"Oliphand","email":"aoliphandg@usnews.com","gender":"Male"},
{"id":18,"first_name":"Igor","last_name":"Paul","email":"ipaulh@ameblo.jp","gender":"Male"},
{"id":19,"first_name":"Catherin","last_name":"Youde","email":"cyoudei@shareasale.com","gender":"Female"},
{"id":20,"first_name":"Jody","last_name":"Ghidetti","email":"jghidettij@ask.com","gender":"Male"},
{"id":21,"first_name":"Isadora","last_name":"Savins","email":"isavinsk@sitemeter.com","gender":"Female"},
{"id":22,"first_name":"Geoff","last_name":"Salack","email":"gsalackl@marketwatch.com","gender":"Male"},
{"id":23,"first_name":"Lombard","last_name":"Bladen","email":"lbladenm@smh.com.au","gender":"Male"},
{"id":24,"first_name":"Betty","last_name":"Panchin","email":"bpanchinn@indiatimes.com","gender":"Female"},
{"id":25,"first_name":"Leeland","last_name":"Vickers","email":"lvickerso@apache.org","gender":"Male"}]

export default names;